import argparse
import os
os.environ["CUDA_VISIBLE_DEVICES"] = "2"
import sys
from pathlib import Path

import clip
import numpy as np
import torch
import torch.nn.functional as F
import torchvision.transforms as T
import wandb
from PIL import Image
from sklearn.model_selection import train_test_split
from torch.utils.data import DataLoader, Dataset
from tqdm.auto import tqdm

# v1 bugfix:
# Allow repo-root package imports when running the script from the scripts
# directory.
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))

from losses.pp_losses import LPIPSScaleLoss
from models.Encoders_v1 import DeltaAwareBlendingModelV1
from models.Net import Net
from models.face_parsing.model import BiSeNet, seg_mean, seg_std
from utils.bicubic import BicubicDownSample
from utils.train import WandbLogger, get_fid_calc, image_grid, seed_everything, toggle_grad


# ============================================================
# USER CONFIG AREA: edit only this block
# ------------------------------------------------------------
# Which GPU / device to use.
# Examples:
# "cuda"
# "cuda:0"
# "cuda:1"
# "cuda:2"
# "cpu"
USER_DEVICE = "cuda"
#
# Blending dataset directory generated by blending_gen_v1.py
USER_DATASET_DIR = Path("images/blending_dataset_v1_rotatebest")
#
# FFHQ image root used to load face and color reference images
USER_FFHQ_ROOT = Path("images/FFHQ")
#
# Real-image directory used to build FID statistics.
# Put your real reference images here, for example:
# Path("fid_images")
USER_FID_IMAGE_DIR = Path("fid_images")
#
# Frozen StyleGAN checkpoint used by this trainer
USER_STYLEGAN_CKPT = "pretrained_models/StyleGAN/ffhq.pt"
#
# Local output root.
# Checkpoints will be saved to:
#   USER_OUTPUT_DIR / "checkpoints"
# Validation preview images will be saved to:
#   USER_OUTPUT_DIR / "val_images"
USER_OUTPUT_DIR = Path("output/blending_train_v1_rotatebest_new")
#
# Run name shown in wandb and used in local save folders
USER_RUN_NAME = "delta_blending_v1_rotatebest_new"
#
# Fixed validation split size.
# If your dataset has fewer than 513 triplets, reduce this value.
USER_VAL_SET_SIZE = 512
#
# Number of validation images logged to wandb each validate call
USER_WANDB_VAL_IMAGES = 100
#
# Number of validation preview images saved locally each validate call
USER_LOCAL_VAL_IMAGES = 100
#
# Save a full resumable checkpoint every N epochs.
# The file will be written to:
#   USER_OUTPUT_DIR / "checkpoints" / "checkpoint.pth"
USER_SAVE_CHECKPOINT_EVERY = 3
#
# Save local validation preview images every N epochs.
# Wandb logging still happens every validation call; this only controls
# writing png files to USER_OUTPUT_DIR / "val_images".
USER_SAVE_VAL_IMAGES_EVERY = 1
#
# Real per-step micro batch size that fits on your GPU
USER_BATCH_SIZE = 8
#
# Target effective batch size after gradient accumulation
# Example:
#   batch_size = 4
#   effective_batch_size = 16
#   grad_accum_steps = 4
#
# Important:
# To match batch=16 exactly, batch_size must divide 16.
# So batch_size 4 or 8 works, but 12 does NOT.
USER_EFFECTIVE_BATCH_SIZE = 16
#
# Total training epochs
USER_EPOCHS = 200
#
# Learning rate
USER_LR = 1e-4
#
# DataLoader workers
USER_NUM_WORKERS = 8
#
# Enable cudnn benchmark for fixed-size inputs. Usually speeds up training
# without changing the optimization target.
USER_CUDNN_BENCHMARK = True
#
# Keep worker processes alive between epochs to reduce DataLoader overhead.
USER_PERSISTENT_WORKERS = True
#
# Prefetch factor per worker when num_workers > 0
USER_PREFETCH_FACTOR = 2
#
# Resume checkpoint path; keep None for training from scratch
USER_CHECKPOINT = None
# ============================================================


# v1 modification:
# This trainer is rewritten for the delta-aware blending architecture.
# It consumes explicit add/remove/boundary masks and supervises
# texture transfer plus disocclusion cleanup.


MASK_KEYS = ["M_src", "M_tgt", "M_add", "M_remove", "M_keep", "M_boundary", "M_color"]


def resolve_image_path(root: Path, stem: str) -> Path:
    for suffix in (".png", ".jpg", ".jpeg"):
        candidate = root / f"{stem}{suffix}"
        if candidate.is_file():
            return candidate
    raise FileNotFoundError(f"Cannot find image for stem {stem} in {root}")


def load_mask(array: np.ndarray) -> torch.Tensor:
    tensor = torch.from_numpy(array).float()
    while tensor.ndim > 3:
        tensor = tensor.squeeze(0)
    if tensor.ndim == 2:
        tensor = tensor.unsqueeze(0)
    return tensor


class DeltaBlendingDatasetV1(Dataset):
    def __init__(self, exps, dataset_root: Path, ffhq_root: Path):
        super().__init__()
        self.exps = exps
        self.dataset_root = dataset_root
        self.ffhq_root = ffhq_root
        self.to_tensor = T.ToTensor()
        self.normalize = T.Normalize([0.5, 0.5, 0.5], [0.5, 0.5, 0.5])

    def __len__(self):
        return len(self.exps)

    def _load_image(self, stem: str) -> torch.Tensor:
        image = Image.open(resolve_image_path(self.ffhq_root, stem)).convert("RGB")
        return self.normalize(self.to_tensor(image.resize((256, 256), resample=Image.LANCZOS)))

    def __getitem__(self, idx):
        im1, im2, im3 = self.exps[idx]

        face_fs = np.load(self.dataset_root / "FS" / f"{im1}.npz")
        color_fs = np.load(self.dataset_root / "FS" / f"{im3}.npz")
        align_npz = np.load(self.dataset_root / "Align" / f"{im1}_{im2}.npz")
        delta_npz = np.load(self.dataset_root / "Delta" / f"{im1}_{im2}_{im3}.npz")

        face_latent = torch.from_numpy(face_fs["latent_in"]).float().squeeze(0)
        color_latent = torch.from_numpy(color_fs["latent_in"]).float().squeeze(0)
        align_f = torch.from_numpy(align_npz["latent_F_align"]).float().squeeze(0)

        masks = torch.stack([load_mask(delta_npz[key]) for key in MASK_KEYS], dim=0).squeeze(1)
        face_img = self._load_image(im1)
        color_img = self._load_image(im3)
        return face_latent, color_latent, align_f, face_img, color_img, masks


class ClipRegionEncoderV1(torch.nn.Module):
    def __init__(self, device: str):
        super().__init__()
        self.clip_model, _ = clip.load("ViT-B/32", device=device)
        self.transform = T.Compose(
            [T.Normalize((0.48145466, 0.4578275, 0.40821073), (0.26862954, 0.26130258, 0.27577711))]
        )
        self.face_pool = torch.nn.AdaptiveAvgPool2d((224, 224))
        for param in self.clip_model.parameters():
            param.requires_grad = False

    def forward(self, image_tensor: torch.Tensor) -> torch.Tensor:
        resized_tensor = self.face_pool(image_tensor * 0.5 + 0.5)
        renormed_tensor = self.transform(resized_tensor)
        return self.clip_model.encode_image(renormed_tensor)


class TrainerV1:
    def __init__(self, model, optimizer, train_dataloader, test_dataloader, logger, args):
        self.model = model
        self.optimizer = optimizer
        self.train_dataloader = train_dataloader
        self.test_dataloader = test_dataloader
        self.logger = logger
        self.args = args
        self.device = args.device if (torch.cuda.is_available() or args.device == "cpu") else "cpu"
        self.grad_accum_steps = args.grad_accum_steps
        self.output_dir = Path(args.output_dir)
        self.ckpt_dir = self.output_dir / "checkpoints"
        self.preview_dir = self.output_dir / "val_images"
        self.ckpt_dir.mkdir(parents=True, exist_ok=True)
        self.preview_dir.mkdir(parents=True, exist_ok=True)
        self.validate_calls = 0
        self.wandb_val_images = args.wandb_val_images
        self.local_val_images = args.local_val_images
        self.save_checkpoint_every = args.save_checkpoint_every
        self.save_val_images_every = args.save_val_images_every
        self.fid_calc = None

        self.net = Net(
            argparse.Namespace(
                size=1024,
                ckpt=args.stylegan_ckpt,
                channel_multiplier=2,
                latent=512,
                n_mlp=8,
                device=self.device,
            )
        )
        self.clip_encoder = ClipRegionEncoderV1(self.device).to(self.device).eval()
        self.lpips = LPIPSScaleLoss().to(self.device).eval()
        self.seg = BiSeNet(n_classes=16).to(self.device).eval()
        self.seg.load_state_dict(torch.load("pretrained_models/BiSeNet/seg.pth", map_location=self.device))

        toggle_grad(self.clip_encoder, False)
        toggle_grad(self.seg, False)
        toggle_grad(self.net.generator, False)

        self.downsample_512 = BicubicDownSample(factor=2)
        self.downsample_256 = BicubicDownSample(factor=4)
        self.best_loss = float("+inf")

        if args.fid_image_dir:
            fid_dir = Path(args.fid_image_dir)
            if fid_dir.is_dir():
                self.fid_calc = get_fid_calc(
                    instance=str(self.output_dir / "fid_blending_v1.pkl"),
                    dataset_path=str(fid_dir),
                    device=torch.device(self.device),
                )
            else:
                print(f"[warning] fid_image_dir does not exist, skip FID: {fid_dir}")

    def _decode(self, face_latent, color_latent, align_f, face_img, color_img, masks):
        mask_dict = {key: masks[:, idx : idx + 1].to(self.device) for idx, key in enumerate(MASK_KEYS)}
        state = self.model(
            face_latent[:, 6:],
            color_latent[:, 6:],
            face_img,
            color_img,
            mask_dict,
        )
        latent_in = torch.cat((face_latent[:, :6], state["latent_tail"]), dim=1)
        context_mask = F.interpolate(
            (mask_dict["M_remove"] + 0.5 * mask_dict["M_boundary"]).clamp(0, 1),
            size=(32, 32),
            mode="bilinear",
            align_corners=False,
        )
        latent_f = align_f + context_mask * state["boundary_gate"] * state["delta_F"]
        images, _ = self.net.generator(
            [latent_in],
            input_is_latent=True,
            return_latents=False,
            start_layer=4,
            end_layer=8,
            layer_in=latent_f,
        )
        return self.downsample_256(images), mask_dict

    def _masked_l1(self, pred, target, mask):
        denom = (mask.sum() * pred.size(1)).clamp_min(1.0)
        return (torch.abs(pred - target) * mask).sum() / denom

    @torch.no_grad()
    def _hair_probability(self, image_0_1: torch.Tensor):
        im = (self.downsample_512(image_0_1) - seg_mean) / seg_std
        logits, _, _ = self.seg(im)
        prob = torch.softmax(logits, dim=1)[:, 10:11]
        return F.interpolate(prob, size=(256, 256), mode="bilinear", align_corners=False)

    def calc_loss(self, generated_256, face_img, color_img, masks):
        gen_0_1 = ((generated_256 + 1) / 2).clip(0, 1)
        face_0_1 = ((face_img + 1) / 2).clip(0, 1)

        preserve_mask = (1 - masks["M_tgt"]).clamp(0, 1)
        hair_mask = masks["M_tgt"]
        remove_mask = masks["M_remove"]
        boundary_mask = masks["M_boundary"]
        color_mask = masks["M_color"]

        face_embed = self.clip_encoder(face_img * preserve_mask)
        gen_face_embed = self.clip_encoder(generated_256 * preserve_mask)
        hair_embed = self.clip_encoder(color_img * color_mask)
        gen_hair_embed = self.clip_encoder(generated_256 * hair_mask)

        losses = {
            "face clip": (1 - F.cosine_similarity(gen_face_embed, face_embed)).mean(),
            "hair clip": (1 - F.cosine_similarity(gen_hair_embed, hair_embed)).mean(),
            "remove l1": 2.0 * self._masked_l1(gen_0_1, face_0_1, remove_mask),
            "boundary l1": 1.5 * self._masked_l1(gen_0_1, face_0_1, boundary_mask),
            "hair lpips": 0.5 * self.lpips(generated_256 * hair_mask, color_img * color_mask),
        }

        hair_prob = self._hair_probability(gen_0_1)
        losses["remove hair suppress"] = 2.0 * (hair_prob * remove_mask).mean()
        losses["loss"] = sum(losses.values())
        return losses

    def train_one_epoch(self):
        self.model.to(self.device).train()
        self.optimizer.zero_grad(set_to_none=True)
        total_batches = len(self.train_dataloader)

        for batch_idx, batch in enumerate(tqdm(self.train_dataloader), start=1):
            face_latent, color_latent, align_f, face_img, color_img, masks = batch
            face_latent = face_latent.to(self.device)
            color_latent = color_latent.to(self.device)
            align_f = align_f.to(self.device)
            face_img = face_img.to(self.device)
            color_img = color_img.to(self.device)
            masks = masks.to(self.device)

            generated_256, mask_dict = self._decode(face_latent, color_latent, align_f, face_img, color_img, masks)
            losses = self.calc_loss(generated_256, face_img, color_img, mask_dict)

            # Gradient accumulation:
            # divide the loss by grad_accum_steps so the accumulated gradient
            # matches the target effective batch size.
            (losses["loss"] / self.grad_accum_steps).backward()

            should_step = (batch_idx % self.grad_accum_steps == 0) or (batch_idx == total_batches)
            grad_norm = None
            if should_step:
                grad_norm = torch.nn.utils.clip_grad_norm_(self.model.parameters(), 5.0)
                self.optimizer.step()
                self.optimizer.zero_grad(set_to_none=True)

            self.logger.next_step()
            for key, val in losses.items():
                self.logger.log(key, val.item())
            self.logger.log("grad_accum_steps", self.grad_accum_steps)
            if grad_norm is not None:
                self.logger.log("grad", grad_norm.item())

    @torch.no_grad()
    def validate(self, epoch: int | None = None):
        self.model.to(self.device).eval()
        summed = {}
        files = []
        images_to_fid = []
        to_299 = T.Resize((299, 299))

        for batch in tqdm(self.test_dataloader):
            face_latent, color_latent, align_f, face_img, color_img, masks = batch
            face_latent = face_latent.to(self.device)
            color_latent = color_latent.to(self.device)
            align_f = align_f.to(self.device)
            face_img = face_img.to(self.device)
            color_img = color_img.to(self.device)
            masks = masks.to(self.device)

            generated_256, mask_dict = self._decode(face_latent, color_latent, align_f, face_img, color_img, masks)
            losses = self.calc_loss(generated_256, face_img, color_img, mask_dict)

            for key, val in losses.items():
                summed[key] = summed.get(key, 0.0) + val.item()

            if self.fid_calc is not None:
                images_to_fid.append(to_299(((generated_256 + 1) / 2).clamp(0, 1)))

            for idx in range(generated_256.size(0)):
                files.append(
                    [
                        T.functional.to_pil_image(((color_img[idx] + 1) / 2).clamp(0, 1).cpu()),
                        T.functional.to_pil_image(((face_img[idx] + 1) / 2).clamp(0, 1).cpu()),
                        T.functional.to_pil_image(((generated_256[idx] + 1) / 2).clamp(0, 1).cpu()),
                    ]
                )

        for key, val in summed.items():
            self.logger.log(f"val {key}", val / len(self.test_dataloader))

        if self.fid_calc is not None and images_to_fid:
            fid_value = self.fid_calc(torch.cat(images_to_fid)).item()
            self.logger.log("val FID CLIP", fid_value)

        np.random.seed(1927)
        sample_size = min(len(files), max(self.wandb_val_images, self.local_val_images))
        idxs = np.random.choice(len(files), size=sample_size, replace=False)
        val_grids = [image_grid(files[idx], 1, 3) for idx in idxs]
        self.logger.log("val images", [wandb.Image(grid) for grid in val_grids[: self.wandb_val_images]])

        # Save local preview images so the user can inspect the training outputs
        # without opening wandb.
        should_save_local_val = epoch is None or ((epoch + 1) % self.save_val_images_every == 0)
        if should_save_local_val:
            for save_idx, grid in enumerate(val_grids[: min(len(val_grids), self.local_val_images)]):
                grid.save(self.preview_dir / f"val_{self.validate_calls:04d}_{save_idx:02d}.png")
        self.validate_calls += 1

        return summed["loss"] / len(self.test_dataloader)

    def save_model(self, name):
        path = self.ckpt_dir / f"{name}.pth"
        torch.save({"model_state_dict": self.model.state_dict()}, path)
        self.logger.save(str(path), save_online=False)

    def save_checkpoint(self, epoch: int):
        checkpoint_path = self.ckpt_dir / "checkpoint.pth"
        torch.save(
            {
                "epoch": epoch,
                "model_state_dict": self.model.state_dict(),
                "optimizer_state_dict": self.optimizer.state_dict(),
                "best_loss": self.best_loss,
                "validate_calls": self.validate_calls,
            },
            checkpoint_path,
        )
        self.logger.save(str(checkpoint_path), save_online=False)

    def train_loop(self, epochs: int):
        self.validate(epoch=None)
        for epoch in range(epochs):
            self.train_one_epoch()
            loss = self.validate(epoch=epoch)
            self.save_model("last")
            if (epoch + 1) % self.save_checkpoint_every == 0:
                self.save_checkpoint(epoch)
            if loss <= self.best_loss:
                self.best_loss = loss
                self.save_model("best")


def main(args):
    seed_everything()

    torch.backends.cudnn.benchmark = bool(args.cudnn_benchmark)

    if args.batch_size <= 0:
        raise ValueError("batch_size must be > 0")
    if args.effective_batch_size <= 0:
        raise ValueError("effective_batch_size must be > 0")
    if args.save_checkpoint_every <= 0:
        raise ValueError("save_checkpoint_every must be > 0")
    if args.save_val_images_every <= 0:
        raise ValueError("save_val_images_every must be > 0")
    if args.effective_batch_size % args.batch_size != 0:
        raise ValueError(
            "effective_batch_size must be divisible by batch_size to reproduce an exact effective batch. "
            f"Got batch_size={args.batch_size}, effective_batch_size={args.effective_batch_size}. "
            "For effective batch 16, use batch_size 4 or 8 instead of 12."
        )

    args.grad_accum_steps = max(1, args.effective_batch_size // args.batch_size)
    args.output_dir = Path(args.output_dir)
    args.output_dir.mkdir(parents=True, exist_ok=True)

    exps = []
    with open(args.dataset / "dataset.exps", "r") as file:
        for exp in file.readlines():
            exps.append(exp.split())

    if len(exps) <= args.val_set_size:
        raise ValueError(
            f"Dataset has only {len(exps)} triplets, but val_set_size is fixed to {args.val_set_size}. "
            "Reduce USER_VAL_SET_SIZE or generate a larger dataset."
        )
    x_train, x_test = train_test_split(exps, test_size=args.val_set_size, random_state=42)

    train_dataset = DeltaBlendingDatasetV1(x_train, args.dataset, args.FFHQ)
    test_dataset = DeltaBlendingDatasetV1(x_test, args.dataset, args.FFHQ)

    train_loader = DataLoader(
        train_dataset,
        batch_size=args.batch_size,
        shuffle=True,
        drop_last=True,
        num_workers=args.num_workers,
        pin_memory=True,
        persistent_workers=bool(args.persistent_workers and args.num_workers > 0),
        prefetch_factor=args.prefetch_factor if args.num_workers > 0 else None,
    )
    test_loader = DataLoader(
        test_dataset,
        batch_size=args.batch_size,
        shuffle=False,
        num_workers=args.num_workers,
        pin_memory=True,
        persistent_workers=bool(args.persistent_workers and args.num_workers > 0),
        prefetch_factor=args.prefetch_factor if args.num_workers > 0 else None,
    )

    logger = WandbLogger(name=args.name_run, project="HairFast-Blending-v1")
    logger.start_logging()
    logger.save(__file__)

    model = DeltaAwareBlendingModelV1()
    if args.checkpoint and os.path.isfile(args.checkpoint):
        model.load_state_dict(torch.load(args.checkpoint, map_location=args.device)["model_state_dict"], strict=False)

    optimizer = torch.optim.Adam(model.parameters(), lr=args.lr, weight_decay=1e-6)
    trainer = TrainerV1(model, optimizer, train_loader, test_loader, logger, args)
    trainer.train_loop(args.epochs)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Delta-aware blending trainer")
    parser.add_argument("--name_run", type=str, default=USER_RUN_NAME)
    parser.add_argument("--dataset", type=Path, default=USER_DATASET_DIR)
    parser.add_argument("--FFHQ", type=Path, default=USER_FFHQ_ROOT)
    parser.add_argument("--fid_image_dir", type=Path, default=USER_FID_IMAGE_DIR)
    parser.add_argument("--device", type=str, default=USER_DEVICE)
    parser.add_argument("--stylegan_ckpt", type=str, default=USER_STYLEGAN_CKPT)
    parser.add_argument("--output_dir", type=Path, default=USER_OUTPUT_DIR)
    parser.add_argument("--val_set_size", type=int, default=USER_VAL_SET_SIZE)
    parser.add_argument("--wandb_val_images", type=int, default=USER_WANDB_VAL_IMAGES)
    parser.add_argument("--local_val_images", type=int, default=USER_LOCAL_VAL_IMAGES)
    parser.add_argument("--save_checkpoint_every", type=int, default=USER_SAVE_CHECKPOINT_EVERY)
    parser.add_argument("--save_val_images_every", type=int, default=USER_SAVE_VAL_IMAGES_EVERY)
    parser.add_argument("--batch_size", type=int, default=USER_BATCH_SIZE)
    parser.add_argument("--effective_batch_size", type=int, default=USER_EFFECTIVE_BATCH_SIZE)
    parser.add_argument("--epochs", type=int, default=USER_EPOCHS)
    parser.add_argument("--lr", type=float, default=USER_LR)
    parser.add_argument("--num_workers", type=int, default=USER_NUM_WORKERS)
    parser.add_argument("--cudnn_benchmark", type=int, default=int(USER_CUDNN_BENCHMARK))
    parser.add_argument("--persistent_workers", type=int, default=int(USER_PERSISTENT_WORKERS))
    parser.add_argument("--prefetch_factor", type=int, default=USER_PREFETCH_FACTOR)
    parser.add_argument("--checkpoint", type=str, default=USER_CHECKPOINT)
    args = parser.parse_args()

    main(args)
