import random
import sys
import time
from pathlib import Path

import numpy as np


sys.path.append(str(Path(__file__).resolve().parents[1]))


# ========================= USER CONFIG: edit only this block =========================
# Dataset directory generated by blending_gen_v4.py
USER_DATASET_DIR = Path("input/blending_dataset_v4")

# FFHQ image directory used to read original face / shape / color images
USER_FFHQ_ROOT = Path("images/FFHQ")

# Expected final triplet count. Set to None to skip percentage progress.
USER_TARGET_SIZE = 3000

# Run once if 0. Set to 30 or 60 if you want to monitor the folder continuously.
USER_WATCH_SECONDS = 0

# How many fully-complete triplets to sample for .npz health checking
USER_HEALTH_SAMPLE_COUNT = 32

# Whether to render random preview images for visual inspection
USER_MAKE_PREVIEW = False

# How many preview sheets to export
USER_PREVIEW_COUNT = 8

# Preview output directory
USER_PREVIEW_DIR = Path("output/check_blending_gen_v4")

# Use "cpu" if training is still occupying the GPU
USER_DEVICE = "cpu"

# StyleGAN checkpoint used only when USER_MAKE_PREVIEW=True
USER_STYLEGAN_CKPT = "pretrained_models/StyleGAN/ffhq.pt"

# Random seed for reproducible sampling
USER_RANDOM_SEED = 3407
# ====================================================================================


def read_triplets(dataset_exps: Path) -> list[tuple[str, str, str]]:
    if not dataset_exps.exists():
        return []

    triplets: list[tuple[str, str, str]] = []
    with open(dataset_exps, "r", encoding="utf-8") as f:
        for line in f:
            items = line.strip().split()
            if len(items) == 3:
                triplets.append((items[0], items[1], items[2]))
    return triplets


def expected_paths(dataset_dir: Path, face: str, shape: str, color: str) -> dict[str, Path]:
    return {
        "fs_face": dataset_dir / "FS" / f"{face}.npz",
        "fs_shape": dataset_dir / "FS" / f"{shape}.npz",
        "fs_color": dataset_dir / "FS" / f"{color}.npz",
        "align_shape": dataset_dir / "Align" / f"{face}_{shape}.npz",
        "align_color": dataset_dir / "Align" / f"{face}_{color}.npz",
    }


def summarize_once(dataset_dir: Path, target_size: int | None):
    exps_path = dataset_dir / "dataset.exps"
    triplets = read_triplets(exps_path)

    fs_dir = dataset_dir / "FS"
    align_dir = dataset_dir / "Align"
    fs_files = list(fs_dir.glob("*.npz")) if fs_dir.exists() else []
    align_files = list(align_dir.glob("*.npz")) if align_dir.exists() else []

    complete: list[tuple[str, str, str]] = []
    incomplete: list[tuple[tuple[str, str, str], list[str]]] = []
    missing_counter = {
        "fs_face": 0,
        "fs_shape": 0,
        "fs_color": 0,
        "align_shape": 0,
        "align_color": 0,
    }

    for triplet in triplets:
        paths = expected_paths(dataset_dir, *triplet)
        missing = [name for name, path in paths.items() if not path.exists()]
        if missing:
            incomplete.append((triplet, missing))
            for name in missing:
                missing_counter[name] += 1
        else:
            complete.append(triplet)

    print("=" * 88)
    print(f"dataset dir:              {dataset_dir.resolve()}")
    print(f"dataset.exps exists:      {exps_path.exists()}")
    print(f"written triplets:         {len(triplets)}")
    if target_size is not None:
        print(f"target triplets:          {target_size}")
        print(f"written progress:         {len(triplets)}/{target_size} = {len(triplets) / max(target_size, 1):.2%}")
        print(f"complete progress:        {len(complete)}/{target_size} = {len(complete) / max(target_size, 1):.2%}")
    print(f"fully complete triplets:  {len(complete)}")
    print(f"incomplete triplets:      {len(incomplete)}")
    print(f"FS npz count:             {len(fs_files)}")
    print(f"Align npz count:          {len(align_files)}")

    print("\nmissing breakdown:")
    for key, value in missing_counter.items():
        print(f"  {key:12s}: {value}")

    if incomplete:
        print("\nexample incomplete triplets:")
        for triplet, missing in incomplete[:5]:
            print(f"  {triplet} -> missing {missing}")

    if triplets:
        print("\nlast 5 triplets in dataset.exps:")
        for triplet in triplets[-5:]:
            paths = expected_paths(dataset_dir, *triplet)
            is_complete = all(path.exists() for path in paths.values())
            status = "complete" if is_complete else "incomplete"
            print(f"  {triplet} [{status}]")

    return triplets, complete


def check_npz_health(dataset_dir: Path, complete_triplets: list[tuple[str, str, str]], sample_count: int):
    if not complete_triplets or sample_count <= 0:
        return

    sample_count = min(sample_count, len(complete_triplets))
    samples = random.sample(complete_triplets, sample_count)
    bad_files: list[tuple[tuple[str, str, str], str, str]] = []

    for triplet in samples:
        for name, path in expected_paths(dataset_dir, *triplet).items():
            try:
                data = np.load(path)
                for key in data.files:
                    arr = data[key]
                    if not np.isfinite(arr).all():
                        bad_files.append((triplet, str(path), f"{name}:{key} has NaN/Inf"))
            except Exception as exc:
                bad_files.append((triplet, str(path), repr(exc)))

    print("\nnpz health check:")
    print(f"  sampled complete triplets: {sample_count}")
    if not bad_files:
        print("  result: all sampled npz files are readable and finite")
    else:
        print(f"  result: found {len(bad_files)} issues")
        for triplet, path, reason in bad_files[:10]:
            print(f"  BAD {triplet} | {path} | {reason}")


def resolve_image(ffhq_root: Path, stem: str) -> Path | None:
    for ext in (".png", ".jpg", ".jpeg"):
        path = ffhq_root / f"{stem}{ext}"
        if path.exists():
            return path
    return None


def make_previews(
    dataset_dir: Path,
    ffhq_root: Path,
    complete_triplets: list[tuple[str, str, str]],
    output_dir: Path,
    stylegan_ckpt: str,
    device: str,
    sample_count: int,
    seed: int,
):
    if sample_count <= 0 or not complete_triplets:
        return

    import torch
    import torch.nn.functional as F
    from PIL import Image, ImageDraw

    from models.Net import Net

    rng = random.Random(seed)
    samples = rng.sample(complete_triplets, min(sample_count, len(complete_triplets)))

    opts = type(
        "TmpOpts",
        (),
        {
            "size": 1024,
            "ckpt": stylegan_ckpt,
            "channel_multiplier": 2,
            "latent": 512,
            "n_mlp": 8,
            "device": device,
        },
    )()
    net = Net(opts)

    output_dir.mkdir(parents=True, exist_ok=True)

    def load_latent(npz_path: Path, key: str):
        arr = np.load(npz_path)[key]
        tensor = torch.from_numpy(arr).float().to(device)
        if tensor.dim() == 2:
            tensor = tensor.unsqueeze(0)
        return tensor

    def tensor_to_pil(img: torch.Tensor):
        if img.dim() == 3:
            img = img.unsqueeze(0)
        img = F.interpolate(img, size=(256, 256), mode="bilinear", align_corners=False)
        img = ((img[0] + 1) / 2).clamp(0, 1).detach().cpu()
        arr = (img.permute(1, 2, 0).numpy() * 255).astype(np.uint8)
        return Image.fromarray(arr)

    def read_pil(path: Path):
        return Image.open(path).convert("RGB").resize((256, 256))

    @torch.no_grad()
    def render(face_s, align_f):
        out, _ = net.generator(
            [face_s],
            input_is_latent=True,
            return_latents=False,
            start_layer=4,
            end_layer=8,
            layer_in=align_f,
        )
        return out

    for idx, (face, shape, color) in enumerate(samples):
        face_image = resolve_image(ffhq_root, face)
        shape_image = resolve_image(ffhq_root, shape)
        color_image = resolve_image(ffhq_root, color)
        if not face_image or not shape_image or not color_image:
            print(f"skip preview for {(face, shape, color)} because source image is missing")
            continue

        paths = expected_paths(dataset_dir, face, shape, color)
        try:
            face_s = load_latent(paths["fs_face"], "latent_in")
            align_shape_f = load_latent(paths["align_shape"], "latent_F")
            align_color_f = load_latent(paths["align_color"], "latent_F")

            preview_shape = tensor_to_pil(render(face_s, align_shape_f))
            preview_color = tensor_to_pil(render(face_s, align_color_f))
        except Exception as exc:
            print(f"preview failed for {(face, shape, color)}: {exc}")
            continue

        columns = [
            ("face", read_pil(face_image)),
            ("shape", read_pil(shape_image)),
            ("color", read_pil(color_image)),
            ("face + Align(face,shape)", preview_shape),
            ("face + Align(face,color)", preview_color),
        ]

        canvas = Image.new("RGB", (256 * len(columns), 284), color=(255, 255, 255))
        draw = ImageDraw.Draw(canvas)
        for col_idx, (title, image) in enumerate(columns):
            x = 256 * col_idx
            canvas.paste(image, (x, 28))
            draw.text((x + 6, 6), title, fill=(0, 0, 0))

        out_path = output_dir / f"{idx:03d}_{face}__{shape}__{color}.png"
        canvas.save(out_path)

    print(f"\npreview directory: {output_dir.resolve()}")


def main():
    random.seed(USER_RANDOM_SEED)

    while True:
        _, complete_triplets = summarize_once(USER_DATASET_DIR, USER_TARGET_SIZE)
        check_npz_health(USER_DATASET_DIR, complete_triplets, USER_HEALTH_SAMPLE_COUNT)

        if USER_MAKE_PREVIEW:
            make_previews(
                dataset_dir=USER_DATASET_DIR,
                ffhq_root=USER_FFHQ_ROOT,
                complete_triplets=complete_triplets,
                output_dir=USER_PREVIEW_DIR,
                stylegan_ckpt=USER_STYLEGAN_CKPT,
                device=USER_DEVICE,
                sample_count=USER_PREVIEW_COUNT,
                seed=USER_RANDOM_SEED,
            )

        if USER_WATCH_SECONDS <= 0:
            break

        print(f"\nsleep {USER_WATCH_SECONDS}s, press Ctrl+C to stop watching\n")
        time.sleep(USER_WATCH_SECONDS)


if __name__ == "__main__":
    main()
