from __future__ import annotations

import argparse
import json
import os
import random
import re
import sys
from argparse import Namespace
from pathlib import Path


# ========================= User Config: edit here only =========================
USER_CUDA_VISIBLE_DEVICES = "0"  # GPU id string passed to CUDA_VISIBLE_DEVICES. Use "" to keep shell setting.
USER_DEVICE = "cuda"  # Runtime device. Use "cuda" for training.

USER_DATASET_DIR = Path("images/pp_dataset_e1_small")  # Directory generated by scripts/pp_gen_e1.py.
USER_OUTPUT_DIR = Path("output/pp_e1_checkpoints_small")  # Directory for checkpoints and validation panels.
USER_RUN_NAME = "pp_e1_satd_blendingv8_earring_restore"  # Name stored in train_config.json.

USER_BASE_CHECKPOINT = "pretrained_models/PostProcess/pp_model.pth"  # Initial author PP checkpoint.
USER_RESUME_CHECKPOINT = None  # Explicit checkpoint to resume. None means use auto-resume if enabled.
USER_AUTO_RESUME_LAST = True  # If True, resume USER_OUTPUT_DIR/last.pth when present.

USER_BATCH_SIZE = 4  # Per-step batch size.
USER_NUM_WORKERS = 0  # DataLoader workers. Keep 0 if debugging or running on Windows.
USER_EPOCHS = 80  # Total number of training epochs.
USER_VAL_SIZE = 64  # Number of dataset records used for validation.
USER_VAL_PREVIEW_COUNT = 32  # Number of validation comparison panels saved per validation pass.
USER_GRAD_ACCUM_STEPS = 1  # Effective batch size = batch_size * grad_accum_steps.
USER_SAVE_EVERY_EPOCHS = 10  # Save epoch_XXXX.pth every N epochs. 0 disables periodic checkpoints.

USER_LEARNING_RATE = 1e-4  # Adam learning rate for PP.
USER_PRETRAIN = False  # True trains latent reconstruction warmup as in author script.
USER_FINETUNE_ENCODER = False  # True allows ArcFace/encoder_face gradients.
USER_USE_MOD = True  # Use modulation modules for latent output.
USER_USE_FULL = True  # True concatenates full face/hair features; False uses target_mask feature split.

USER_LOSS_MODE = "author"  # "author" uses losses/pp_losses.py. "l1" is a lightweight fallback.
USER_ITER_BEFORE_ADV = 10_000  # Iteration before adversarial branch starts.
USER_D_REG_EVERY = 16  # Discriminator R1 interval when adversarial branch is enabled.
USER_INPAINT = 0.0  # Author inpaint loss coefficient.
USER_USE_ADV = False  # Enable StyleGAN discriminator adversarial loss.
USER_ADV_COEF = 0.05  # Generator adversarial loss coefficient.

USER_SATD_FACE_NECK_LOSS = 8.0  # Extra L1 anchor: keep PP face/neck close to SATD to prevent shadow rollback. 0 disables.
USER_SATD_FACE_NECK_LABELS = "1,2,16,17"  # CelebA labels anchored to SATD: skin_other, nose, neck_l, neck.
USER_SATD_FACE_NECK_HAIR_EXCLUDE_DILATE = 5  # Dilate target hair mask before excluding it from the SATD anchor.
USER_SATD_FACE_NECK_REPLACE_SOURCE_REF = True  # Use SATD, not original source, as the author loss reference inside face/neck.
USER_SATD_FACE_NECK_REPLACE_TARGET_INPUT = True  # Feed SATD face/neck into PP target encoder while keeping blending hair.

USER_STYLEGAN_CKPT = "pretrained_models/StyleGAN/ffhq.pt"  # StyleGAN2 torch checkpoint.
USER_STYLEGAN_PKL = "pretrained_models/StyleGAN/ffhq.pkl"  # StyleGAN2 discriminator pickle for adversarial loss.

USER_EARRING_RESTORE_ALPHA_STRENGTH = 0.92  # Core alpha strength for validation EarringDirectRestore_e1.
USER_EARRING_RESTORE_ALIGN_MAX_SHIFT = 0  # Default 0 avoids shifted/deformed pasted earrings.
USER_EARRING_RESTORE_ALPHA_FEATHER_STRENGTH = 0.35  # Feather alpha strength for validation restore.
USER_DISABLE_EARRING_RESTORE_WEAK_FALLBACK = False  # True disables weak texture fallback in validation restore.
USER_EARRING_RESTORE_EAR_ROI_DILATE = 11  # Larger ROI recovers longer/drop earrings, but too large may include nearby reflections.
USER_EARRING_RESTORE_PARSER_WEAK_SUPPORT_DILATE = 5  # Support grown around parser earring labels.
USER_EARRING_RESTORE_OBJECT_GROW_ITERS = 1  # Extra object growth inside safe support. Increase to 2 only if earrings are truncated.
USER_EARRING_RESTORE_COMPONENT_KEEP_TOP = 8  # Number of small earring components kept after filtering.
USER_EARRING_RESTORE_COMPONENT_MAX_AREA_RATIO = 0.025  # Max component area ratio; higher recovers larger earrings with more pollution risk.
USER_EARRING_RESTORE_WEAK_HIGH = 0.028  # Weak texture fallback high-frequency threshold. Lower means more recall.
USER_EARRING_RESTORE_WEAK_CHROMA = 0.045  # Weak texture fallback chroma threshold.
USER_EARRING_RESTORE_WEAK_CONTRAST = 0.024  # Weak texture fallback local-contrast threshold.
# ============================================================================ 


if USER_CUDA_VISIBLE_DEVICES:
    os.environ["CUDA_VISIBLE_DEVICES"] = USER_CUDA_VISIBLE_DEVICES

import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
from PIL import Image
from torch.utils.data import DataLoader, Dataset
from torchvision import transforms as T
from torchvision.utils import save_image
from tqdm.auto import tqdm

sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))

from losses.pp_losses import LossBuilder, LossBuilderMulti
from models.EarringDirectRestore_e1 import EarringDirectRestore
from models.Encoders import FeatureEncoderMult, FeatureiResnet, ModulationModule
from models.Net import Net
from models.stylegan2 import dnnlib
from models.stylegan2.model import PixelNorm
from utils.bicubic import BicubicDownSample
from utils.train import _LegacyUnpickler, seed_everything, toggle_grad


def str2path(value):
    return None if value in {None, "", "None"} else Path(value)


def str2bool(value):
    if isinstance(value, bool):
        return value
    value = str(value).strip().lower()
    if value in {"1", "true", "yes", "y"}:
        return True
    if value in {"0", "false", "no", "n"}:
        return False
    raise argparse.ArgumentTypeError(f"Unsupported boolean value: {value}")


def build_parser():
    parser = argparse.ArgumentParser(description="Train PP e1 with EarringDirectRestore_e1 validation panels.")
    parser.add_argument("--dataset_dir", type=Path, default=USER_DATASET_DIR)
    parser.add_argument("--output_dir", type=Path, default=USER_OUTPUT_DIR)
    parser.add_argument("--run_name", type=str, default=USER_RUN_NAME)
    parser.add_argument("--base_checkpoint", type=str2path, default=USER_BASE_CHECKPOINT)
    parser.add_argument("--resume_checkpoint", type=str2path, default=USER_RESUME_CHECKPOINT)
    parser.add_argument("--auto_resume_last", type=str2bool, default=USER_AUTO_RESUME_LAST)
    parser.add_argument("--device", type=str, default=USER_DEVICE)
    parser.add_argument("--batch_size", type=int, default=USER_BATCH_SIZE)
    parser.add_argument("--num_workers", type=int, default=USER_NUM_WORKERS)
    parser.add_argument("--epochs", type=int, default=USER_EPOCHS)
    parser.add_argument("--val_size", type=int, default=USER_VAL_SIZE)
    parser.add_argument("--val_preview_count", type=int, default=USER_VAL_PREVIEW_COUNT)
    parser.add_argument("--grad_accum_steps", type=int, default=USER_GRAD_ACCUM_STEPS)
    parser.add_argument("--save_every_epochs", type=int, default=USER_SAVE_EVERY_EPOCHS)
    parser.add_argument("--lr", type=float, default=USER_LEARNING_RATE)
    parser.add_argument("--pretrain", type=str2bool, default=USER_PRETRAIN)
    parser.add_argument("--finetune", type=str2bool, default=USER_FINETUNE_ENCODER)
    parser.add_argument("--use_mod", type=str2bool, default=USER_USE_MOD)
    parser.add_argument("--use_full", type=str2bool, default=USER_USE_FULL)
    parser.add_argument("--loss_mode", choices=("author", "l1"), default=USER_LOSS_MODE)
    parser.add_argument("--iter_before", type=int, default=USER_ITER_BEFORE_ADV)
    parser.add_argument("--d_reg_every", type=int, default=USER_D_REG_EVERY)
    parser.add_argument("--inpaint", type=float, default=USER_INPAINT)
    parser.add_argument("--use_adv", type=str2bool, default=USER_USE_ADV)
    parser.add_argument("--adv_coef", type=float, default=USER_ADV_COEF)
    parser.add_argument("--satd_face_neck_loss", type=float, default=USER_SATD_FACE_NECK_LOSS)
    parser.add_argument("--satd_face_neck_labels", type=str, default=USER_SATD_FACE_NECK_LABELS)
    parser.add_argument("--satd_face_neck_hair_exclude_dilate", type=int, default=USER_SATD_FACE_NECK_HAIR_EXCLUDE_DILATE)
    parser.add_argument("--satd_face_neck_replace_source_ref", type=str2bool, default=USER_SATD_FACE_NECK_REPLACE_SOURCE_REF)
    parser.add_argument("--satd_face_neck_replace_target_input", type=str2bool, default=USER_SATD_FACE_NECK_REPLACE_TARGET_INPUT)
    parser.add_argument("--stylegan_ckpt", type=str, default=USER_STYLEGAN_CKPT)
    parser.add_argument("--stylegan_pkl", type=str, default=USER_STYLEGAN_PKL)
    parser.add_argument("--earring_restore_alpha_strength", type=float, default=USER_EARRING_RESTORE_ALPHA_STRENGTH)
    parser.add_argument("--earring_restore_align_max_shift", type=int, default=USER_EARRING_RESTORE_ALIGN_MAX_SHIFT)
    parser.add_argument("--earring_restore_alpha_feather_strength", type=float, default=USER_EARRING_RESTORE_ALPHA_FEATHER_STRENGTH)
    parser.add_argument("--disable_earring_restore_weak_fallback", type=str2bool, default=USER_DISABLE_EARRING_RESTORE_WEAK_FALLBACK)
    parser.add_argument("--earring_restore_ear_roi_dilate", type=int, default=USER_EARRING_RESTORE_EAR_ROI_DILATE)
    parser.add_argument("--earring_restore_parser_weak_support_dilate", type=int, default=USER_EARRING_RESTORE_PARSER_WEAK_SUPPORT_DILATE)
    parser.add_argument("--earring_restore_object_grow_iters", type=int, default=USER_EARRING_RESTORE_OBJECT_GROW_ITERS)
    parser.add_argument("--earring_restore_component_keep_top", type=int, default=USER_EARRING_RESTORE_COMPONENT_KEEP_TOP)
    parser.add_argument("--earring_restore_component_max_area_ratio", type=float, default=USER_EARRING_RESTORE_COMPONENT_MAX_AREA_RATIO)
    parser.add_argument("--earring_restore_weak_high", type=float, default=USER_EARRING_RESTORE_WEAK_HIGH)
    parser.add_argument("--earring_restore_weak_chroma", type=float, default=USER_EARRING_RESTORE_WEAK_CHROMA)
    parser.add_argument("--earring_restore_weak_contrast", type=float, default=USER_EARRING_RESTORE_WEAK_CONTRAST)
    return parser


def load_image_01(path: str | Path, size: int = 1024) -> torch.Tensor:
    with Image.open(path) as image:
        image = image.convert("RGB")
        if image.size != (size, size):
            image = image.resize((size, size), Image.BILINEAR)
        return T.functional.to_tensor(image)


def safe_load_image_01(path: str | Path, fallback: torch.Tensor, size: int = 1024) -> torch.Tensor:
    if not path:
        return fallback.clone()
    try:
        return load_image_01(path, size)
    except (FileNotFoundError, OSError):
        return fallback.clone()


def parse_int_list(value: str | tuple[int, ...] | list[int]) -> tuple[int, ...]:
    if isinstance(value, tuple):
        return tuple(int(item) for item in value)
    if isinstance(value, list):
        return tuple(int(item) for item in value)
    value = str(value).strip()
    if not value:
        return ()
    return tuple(int(item.strip()) for item in value.split(",") if item.strip())


def ensure_mask_4d(mask: torch.Tensor) -> torch.Tensor:
    if mask.dim() == 2:
        return mask.unsqueeze(0).unsqueeze(0)
    if mask.dim() == 3:
        return mask.unsqueeze(1) if mask.shape[0] != 1 else mask.unsqueeze(0)
    return mask


def label_mask(parsing: torch.Tensor, labels: tuple[int, ...]) -> torch.Tensor:
    parsing = ensure_mask_4d(parsing).long()
    mask = torch.zeros_like(parsing, dtype=torch.bool)
    for label in labels:
        mask |= parsing == int(label)
    return mask.float()


def dilate_mask(mask: torch.Tensor, kernel_size: int) -> torch.Tensor:
    mask = ensure_mask_4d(mask).float()
    kernel_size = int(kernel_size)
    if kernel_size <= 1:
        return mask.clamp(0, 1)
    if kernel_size % 2 == 0:
        kernel_size += 1
    return F.max_pool2d(mask, kernel_size=kernel_size, stride=1, padding=kernel_size // 2).clamp(0, 1)


def masked_l1(pred: torch.Tensor, target: torch.Tensor, mask: torch.Tensor) -> torch.Tensor:
    mask = ensure_mask_4d(mask).to(device=pred.device, dtype=pred.dtype)
    if mask.shape[-2:] != pred.shape[-2:]:
        mask = F.interpolate(mask, size=pred.shape[-2:], mode="nearest")
    denom = (mask.sum() * pred.shape[1]).clamp_min(1.0)
    return ((pred - target).abs() * mask).sum() / denom


def sorted_dataset_parts(dataset_dir: Path) -> list[Path]:
    def key(path: Path) -> int:
        match = re.search(r"pp_part_(\d+)", path.stem)
        return int(match.group(1)) if match else 0

    parts = sorted(dataset_dir.glob("pp_part_*.dataset"), key=key)
    if not parts:
        raise FileNotFoundError(f"No pp_part_*.dataset files found under {dataset_dir}")
    return parts


def load_records(dataset_dir: Path) -> list[dict[str, object]]:
    records: list[dict[str, object]] = []
    for part in tqdm(sorted_dataset_parts(dataset_dir), desc="Load dataset parts"):
        loaded = torch.load(part, map_location="cpu")
        if not isinstance(loaded, list):
            raise RuntimeError(f"Dataset part must contain a list: {part}")
        records.extend(loaded)
    required = {"source_path", "target", "target_mask", "HT_E", "source_parsing", "target_parsing", "target_hair_mask"}
    records = [record for record in records if required.issubset(record.keys())]
    if len(records) < 2:
        raise RuntimeError("PP e1 dataset must contain at least two valid records.")
    satd_records = sum(1 for record in records if "satd" in record)
    if satd_records < len(records):
        print(
            f"[PP e1] Warning: {len(records) - satd_records}/{len(records)} records have no SATD image. "
            "Face/neck SATD consistency will fall back to the blending target for those records. "
            "Regenerate the dataset with scripts/pp_gen_e1.py --overwrite true for the shadow fix."
        )
    return records


def split_records(records: list[dict[str, object]], val_size: int, seed: int) -> tuple[list[dict[str, object]], list[dict[str, object]]]:
    rng = np.random.default_rng(seed)
    indices = rng.permutation(len(records)).tolist()
    resolved_val = min(max(1, val_size), len(records) - 1)
    val_indices = set(indices[:resolved_val])
    train = [record for idx, record in enumerate(records) if idx not in val_indices]
    val = [record for idx, record in enumerate(records) if idx in val_indices]
    if not train:
        train = val
    return train, val


class PPDatasetE1(Dataset):
    def __init__(self, records: list[dict[str, object]], image_size: int = 1024, is_val: bool = False):
        self.records = records
        self.image_size = image_size
        self.is_val = is_val

    def __len__(self):
        return len(self.records)

    def __getitem__(self, idx):
        record = self.records[idx]
        source_full = load_image_01(record["source_path"], self.image_size)
        satd = record["satd"] if "satd" in record else record["target"]
        blending = record["blending"] if "blending" in record else record["target"]
        shape_path = str(record.get("shape_path", ""))
        color_path = str(record.get("color_path", ""))
        reference_path = color_path or shape_path or str(record["source_path"])
        item = {
            "source_full": source_full,
            "target": record["target"].float(),
            "satd": satd.float(),
            "blending": blending.float(),
            "target_mask": record["target_mask"].float(),
            "HT_E": record["HT_E"].float(),
            "source_parsing": record["source_parsing"].long(),
            "target_parsing": record["target_parsing"].long(),
            "target_hair_mask": record["target_hair_mask"].float(),
            "source_path": str(record["source_path"]),
            "shape_path": shape_path,
            "color_path": color_path,
            "reference_path": reference_path,
        }
        if self.is_val:
            shape_full = safe_load_image_01(shape_path, source_full, self.image_size)
            color_full = safe_load_image_01(color_path, shape_full, self.image_size)
            if shape_path and color_path and shape_path != color_path:
                left_w = self.image_size // 2
                right_w = self.image_size - left_w
                shape_half = T.functional.resize(shape_full, [self.image_size, left_w])
                color_half = T.functional.resize(color_full, [self.image_size, right_w])
                item["reference_full"] = torch.cat([shape_half, color_half], dim=2)
            else:
                item["reference_full"] = color_full
        if not self.is_val and random.random() > 0.5:
            for key in (
                "source_full",
                "target",
                "satd",
                "blending",
                "target_mask",
                "HT_E",
                "source_parsing",
                "target_parsing",
                "target_hair_mask",
            ):
                item[key] = T.functional.hflip(item[key])
        return item


class PostProcessModelE1(nn.Module):
    def __init__(self, args):
        super().__init__()
        self.args = args
        self.encoder_face = FeatureEncoderMult(
            fs_layers=[9],
            opts=argparse.Namespace(arcface_model_path="pretrained_models/ArcFace/backbone_ir50.pth"),
        )
        if not self.args.finetune:
            toggle_grad(self.encoder_face, False)

        self.latent_avg = torch.load("pretrained_models/PostProcess/latent_avg.pt", map_location="cpu")
        self.to_feature = FeatureiResnet([[1024, 2], [768, 2], [512, 2]])

        if self.args.use_mod:
            self.to_latent_1 = nn.ModuleList([ModulationModule(18, i == 4) for i in range(5)])
            self.to_latent_2 = nn.ModuleList([ModulationModule(18, i == 4) for i in range(5)])
            self.pixelnorm = PixelNorm()
        else:
            self.to_latent = nn.Sequential(
                nn.Linear(1024, 1024),
                nn.LayerNorm([1024]),
                nn.LeakyReLU(),
                nn.Linear(1024, 512),
            )

    def forward(self, source, target, target_mask=None, *args, **kwargs):
        s_face, [f_face] = self.encoder_face(source)
        if self.args.pretrain:
            return self.latent_avg.to(source.device) + s_face, f_face

        s_hair, [f_hair] = self.encoder_face(target)
        if self.args.use_mod:
            dt_latent_face = self.pixelnorm(s_face)
            dt_latent_hair = self.pixelnorm(s_hair)
            for mod_module in self.to_latent_1:
                dt_latent_face = mod_module(dt_latent_face, s_hair)
            for mod_module in self.to_latent_2:
                dt_latent_hair = mod_module(dt_latent_hair, s_face)
            final_s = self.latent_avg.to(source.device) + 0.1 * (dt_latent_face + dt_latent_hair)
        else:
            final_s = self.latent_avg.to(source.device) + self.to_latent(torch.cat((s_face, s_hair), dim=-1))

        if self.args.use_full or target_mask is None:
            cat_f = torch.cat((f_face, f_hair), dim=1)
        else:
            t_mask = F.interpolate(target_mask.float(), size=f_face.shape[-2:], mode="nearest")
            cat_f = torch.cat((f_face * t_mask, f_hair * (1 - t_mask)), dim=1)
        return final_s, self.to_feature(cat_f)

    def load_base_checkpoint(self, checkpoint_path: Path | None):
        if checkpoint_path is None:
            return
        checkpoint = torch.load(checkpoint_path, map_location="cpu")
        state_dict = checkpoint.get("model_state_dict", checkpoint)
        result = self.load_state_dict(state_dict, strict=False)
        if result.missing_keys:
            print(f"[PP e1] Missing checkpoint keys: {len(result.missing_keys)}")
        if result.unexpected_keys:
            print(f"[PP e1] Unexpected checkpoint keys: {len(result.unexpected_keys)}")


class TrainerE1:
    def __init__(self, args, model, optimizer, train_loader, val_loader):
        self.args = args
        self.model = model
        self.optimizer = optimizer
        self.train_loader = train_loader
        self.val_loader = val_loader
        self.device = torch.device(args.device if torch.cuda.is_available() else "cpu")
        self.normalize = T.Normalize([0.5, 0.5, 0.5], [0.5, 0.5, 0.5])
        self.downsample_256 = BicubicDownSample(factor=4).to(self.device)
        self.satd_face_neck_labels = parse_int_list(args.satd_face_neck_labels)
        self.net = Net(
            Namespace(
                size=1024,
                ckpt=args.stylegan_ckpt,
                channel_multiplier=2,
                latent=512,
                n_mlp=8,
                device=str(self.device),
            )
        )
        toggle_grad(self.net.generator, False)
        self.earring_restore = EarringDirectRestore(args).to(self.device).eval()

        self.discriminator = None
        self.disc_optim = None
        if args.use_adv:
            with dnnlib.util.open_url(args.stylegan_pkl) as f:
                data = _LegacyUnpickler(f).load()
            self.discriminator = data["D"].to(self.device).eval()
            toggle_grad(self.discriminator, False)
            self.disc_optim = torch.optim.Adam(self.discriminator.parameters(), lr=3e-4, betas=(0.9, 0.999))

        if args.loss_mode == "author":
            loss_config = {"lpips_scale": 0.8, "id": 0.1, "landmark": 0.1, "feat_rec": 0.01, "adv": args.adv_coef, "inpaint": args.inpaint}
            self.loss_builder = LossBuilder(loss_config, device=str(self.device)) if args.pretrain else LossBuilderMulti(loss_config, device=str(self.device))
        else:
            self.loss_builder = None

        self.start_epoch = 1
        self.global_step = 0
        self.best_loss = float("inf")

    def build_satd_face_neck_mask(self, batch, size: tuple[int, int]) -> torch.Tensor | None:
        if not self.satd_face_neck_labels:
            return None

        source_parsing = batch["source_parsing"].to(self.device, non_blocking=True)
        mask = label_mask(source_parsing, self.satd_face_neck_labels)
        if "target_parsing" in batch:
            target_parsing = batch["target_parsing"].to(self.device, non_blocking=True)
            mask = torch.clamp(mask + label_mask(target_parsing, self.satd_face_neck_labels), 0, 1)

        if mask.shape[-2:] != size:
            mask = F.interpolate(mask.float(), size=size, mode="nearest")

        if "target_hair_mask" in batch:
            hair = batch["target_hair_mask"].to(self.device, non_blocking=True).float()
            hair = ensure_mask_4d(hair)
            if hair.shape[-2:] != size:
                hair = F.interpolate(hair, size=size, mode="nearest")
            hair = dilate_mask(hair, self.args.satd_face_neck_hair_exclude_dilate)
            mask = mask * (1 - hair).clamp(0, 1)

        return mask.clamp(0, 1)

    def get_satd_256(self, batch, size: tuple[int, int]) -> torch.Tensor:
        satd = batch["satd"].to(self.device, non_blocking=True).float().clamp(0, 1)
        if satd.shape[-2:] != size:
            satd = F.interpolate(satd, size=size, mode="bilinear", align_corners=False).clamp(0, 1)
        return satd

    def build_source_loss_reference(
        self,
        source: torch.Tensor,
        satd: torch.Tensor,
        satd_mask: torch.Tensor | None,
    ) -> torch.Tensor:
        if not bool(self.args.satd_face_neck_replace_source_ref):
            return source
        if satd_mask is None or satd_mask.detach().sum().item() <= 0:
            return source
        return (source * (1 - satd_mask) + satd * satd_mask).clamp(0, 1)

    def build_target_input_reference(
        self,
        target: torch.Tensor,
        satd: torch.Tensor,
        satd_mask: torch.Tensor | None,
    ) -> torch.Tensor:
        if not bool(self.args.satd_face_neck_replace_target_input):
            return target
        if satd_mask is None or satd_mask.detach().sum().item() <= 0:
            return target
        return (target * (1 - satd_mask) + satd * satd_mask).clamp(0, 1)

    def compute_satd_face_neck_loss(
        self,
        gen_im_F,
        satd: torch.Tensor,
        satd_mask: torch.Tensor | None,
    ) -> torch.Tensor | None:
        coef = float(self.args.satd_face_neck_loss)
        if coef <= 0:
            return None

        gen_f_256 = self.downsample_256((gen_im_F + 1) / 2).clamp(0, 1)
        if satd.shape[-2:] != gen_f_256.shape[-2:]:
            satd = F.interpolate(satd, size=gen_f_256.shape[-2:], mode="bilinear", align_corners=False).clamp(0, 1)
        if satd_mask is None or satd_mask.detach().sum().item() <= 0:
            return None
        return coef * masked_l1(gen_f_256, satd, satd_mask)

    def compute_losses(self, source, target, target_mask, HT_E, gen_im_W, F_w, gen_im_F, latent_f, batch):
        satd = self.get_satd_256(batch, source.shape[-2:])
        satd_mask = self.build_satd_face_neck_mask(batch, source.shape[-2:])
        source_ref = self.build_source_loss_reference(source, satd, satd_mask)

        if self.loss_builder is None:
            gen_f_256 = self.downsample_256((gen_im_F + 1) / 2).clamp(0, 1)
            losses = {"l1": F.l1_loss(gen_f_256 * target_mask, source_ref * target_mask)}
        else:
            losses = self.loss_builder(source_ref, target, target_mask, HT_E, gen_im_W, F_w, gen_im_F, latent_f)

        satd_face_neck = self.compute_satd_face_neck_loss(gen_im_F, satd, satd_mask)
        if satd_face_neck is not None:
            losses["satd_face_neck"] = satd_face_neck
        return losses

    def forward_batch(self, batch):
        source_full = batch["source_full"].to(self.device, non_blocking=True)
        target = batch["target"].to(self.device, non_blocking=True)
        target_mask = batch["target_mask"].to(self.device, non_blocking=True)
        HT_E = batch["HT_E"].to(self.device, non_blocking=True)
        source = self.downsample_256(source_full).clamp(0, 1)
        satd = self.get_satd_256(batch, target.shape[-2:])
        satd_mask = self.build_satd_face_neck_mask(batch, target.shape[-2:])
        target_input = self.build_target_input_reference(target, satd, satd_mask)

        latent_s, latent_f = self.model(self.normalize(source), self.normalize(target_input), target_mask, HT_E)
        gen_im_W, _ = self.net.generator([latent_s], input_is_latent=True, return_latents=False)
        F_w, _ = self.net.generator([latent_s], input_is_latent=True, return_latents=False, start_layer=0, end_layer=4)

        if self.args.pretrain:
            alpha = min(1.0, self.global_step / max(1, self.args.iter_before))
            latent_f_gen = alpha * latent_f + (1 - alpha) * F_w
        else:
            latent_f_gen = latent_f

        gen_im_F, _ = self.net.generator([latent_s], input_is_latent=True, return_latents=False, start_layer=5, end_layer=8, layer_in=latent_f_gen)
        losses = self.compute_losses(source, target, target_mask, HT_E, gen_im_W, F_w, gen_im_F, latent_f, batch)
        losses["loss"] = sum(losses.values())
        return source, target, gen_im_F, losses

    def train_one_epoch(self, epoch: int):
        self.model.to(self.device).train()
        total = 0.0
        steps = 0
        self.optimizer.zero_grad(set_to_none=True)
        accum = max(1, int(self.args.grad_accum_steps))
        pbar = tqdm(self.train_loader, desc=f"Train epoch {epoch}")

        for batch_idx, batch in enumerate(pbar, start=1):
            _, _, _, losses = self.forward_batch(batch)
            (losses["loss"] / accum).backward()
            if batch_idx % accum == 0:
                torch.nn.utils.clip_grad_norm_(self.model.parameters(), 0.5)
                self.optimizer.step()
                self.optimizer.zero_grad(set_to_none=True)
            self.global_step += 1
            total += float(losses["loss"].detach().cpu())
            steps += 1
            pbar.set_postfix(loss=f"{total / max(1, steps):.4f}")

        if steps % accum != 0:
            torch.nn.utils.clip_grad_norm_(self.model.parameters(), 0.5)
            self.optimizer.step()
            self.optimizer.zero_grad(set_to_none=True)
        return total / max(1, steps)

    @torch.no_grad()
    def validate(self, epoch: int):
        self.model.to(self.device).eval()
        val_dir = self.args.output_dir / "val_images" / f"epoch_{epoch:04d}"
        val_dir.mkdir(parents=True, exist_ok=True)
        total = 0.0
        steps = 0
        saved = 0

        for batch in tqdm(self.val_loader, desc=f"Validate epoch {epoch}"):
            _, _, gen_im_F, losses = self.forward_batch(batch)
            gen_f_01 = ((gen_im_F + 1) / 2).clamp(0, 1)
            source_panel = batch["source_full"].to(self.device, non_blocking=True).float().clamp(0, 1)
            reference_panel = batch.get("reference_full", batch["source_full"]).to(self.device, non_blocking=True).float().clamp(0, 1)
            satd_panel = batch["satd"].to(self.device, non_blocking=True).float().clamp(0, 1)
            blending_panel = batch["blending"].to(self.device, non_blocking=True).float().clamp(0, 1)
            restored, _ = self.earring_restore(
                source_image=source_panel,
                pp_out=gen_f_01,
                source_parsing=batch["source_parsing"].to(self.device),
                target_parsing=batch["target_parsing"].to(self.device),
                target_hair_mask=batch["target_hair_mask"].to(self.device),
                enabled=True,
            )

            total += float(losses["loss"].detach().cpu())
            steps += 1

            if saved < self.args.val_preview_count:
                out_size = gen_f_01.shape[-2:]
                if source_panel.shape[-2:] != out_size:
                    source_panel = F.interpolate(source_panel, size=out_size, mode="bilinear", align_corners=False).clamp(0, 1)
                if reference_panel.shape[-2:] != out_size:
                    reference_panel = F.interpolate(reference_panel, size=out_size, mode="bilinear", align_corners=False).clamp(0, 1)
                if satd_panel.shape[-2:] != out_size:
                    satd_panel = F.interpolate(satd_panel, size=out_size, mode="bilinear", align_corners=False).clamp(0, 1)
                if blending_panel.shape[-2:] != out_size:
                    blending_panel = F.interpolate(blending_panel, size=out_size, mode="bilinear", align_corners=False).clamp(0, 1)
                batch_count = min(gen_f_01.size(0), self.args.val_preview_count - saved)
                for idx in range(batch_count):
                    panel = torch.cat(
                        [
                            source_panel[idx].cpu(),
                            reference_panel[idx].cpu(),
                            satd_panel[idx].cpu(),
                            blending_panel[idx].cpu(),
                            gen_f_01[idx].cpu(),
                            restored[idx].cpu(),
                        ],
                        dim=2,
                    )
                    save_image(panel, val_dir / f"sample_{saved:04d}.png")
                    saved += 1

        return total / max(1, steps)

    def save_checkpoint(self, name: str, epoch: int, val_loss: float):
        self.args.output_dir.mkdir(parents=True, exist_ok=True)
        path = self.args.output_dir / name
        torch.save(
            {
                "model_state_dict": self.model.state_dict(),
                "optimizer_state_dict": self.optimizer.state_dict(),
                "epoch": epoch,
                "global_step": self.global_step,
                "best_loss": self.best_loss,
                "val_loss": val_loss,
                "args": vars(self.args),
            },
            path,
        )
        print(f"Saved checkpoint: {path}")

    def load_checkpoint(self, path: Path):
        checkpoint = torch.load(path, map_location="cpu")
        self.model.load_state_dict(checkpoint["model_state_dict"], strict=False)
        if "optimizer_state_dict" in checkpoint:
            self.optimizer.load_state_dict(checkpoint["optimizer_state_dict"])
        self.start_epoch = int(checkpoint.get("epoch", 0)) + 1
        self.global_step = int(checkpoint.get("global_step", 0))
        self.best_loss = float(checkpoint.get("best_loss", float("inf")))
        print(f"Resumed from {path}: start_epoch={self.start_epoch}, best_loss={self.best_loss:.6f}")

    def train_loop(self):
        initial_val = self.validate(epoch=0)
        print(f"Initial val loss: {initial_val:.6f}")
        for epoch in range(self.start_epoch, self.args.epochs + 1):
            train_loss = self.train_one_epoch(epoch)
            val_loss = self.validate(epoch)
            print(f"Epoch {epoch}: train_loss={train_loss:.6f}, val_loss={val_loss:.6f}")

            self.save_checkpoint("last.pth", epoch, val_loss)
            if val_loss <= self.best_loss:
                self.best_loss = val_loss
                self.save_checkpoint("best.pth", epoch, val_loss)
            if self.args.save_every_epochs > 0 and epoch % self.args.save_every_epochs == 0:
                self.save_checkpoint(f"epoch_{epoch:04d}.pth", epoch, val_loss)


def save_config(args):
    args.output_dir.mkdir(parents=True, exist_ok=True)
    with open(args.output_dir / "train_config.json", "w", encoding="utf-8") as handle:
        json.dump({key: str(value) for key, value in vars(args).items()}, handle, ensure_ascii=False, indent=2)


def main(args):
    seed_everything(3407)
    args.output_dir.mkdir(parents=True, exist_ok=True)
    save_config(args)

    records = load_records(args.dataset_dir)
    train_records, val_records = split_records(records, args.val_size, seed=42)
    print(f"Loaded records: train={len(train_records)}, val={len(val_records)}")

    train_dataset = PPDatasetE1(train_records, is_val=False)
    val_dataset = PPDatasetE1(val_records, is_val=True)
    train_loader = DataLoader(train_dataset, batch_size=args.batch_size, shuffle=True, drop_last=True, num_workers=args.num_workers, pin_memory=False)
    val_loader = DataLoader(val_dataset, batch_size=args.batch_size, shuffle=False, drop_last=False, num_workers=args.num_workers, pin_memory=False)

    model = PostProcessModelE1(args)
    optimizer = torch.optim.Adam(filter(lambda p: p.requires_grad, model.parameters()), lr=args.lr, weight_decay=0)
    trainer = TrainerE1(args, model, optimizer, train_loader, val_loader)

    resume_path = args.resume_checkpoint
    if resume_path is None and args.auto_resume_last and (args.output_dir / "last.pth").exists():
        resume_path = args.output_dir / "last.pth"

    if resume_path is not None:
        trainer.load_checkpoint(resume_path)
    elif args.base_checkpoint is not None:
        model.load_base_checkpoint(args.base_checkpoint)

    trainer.train_loop()


if __name__ == "__main__":
    main(build_parser().parse_args())
